/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateEventRouteImport } from './routes/create-event'
import { Route as ClosedRouteImport } from './routes/closed'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as SlugAdminIndexRouteImport } from './routes/$slug.admin.index'
import { Route as ApiPublicExpireEventsRouteImport } from './routes/api/public/expire-events'
import { Route as SlugAdminDashboardRouteImport } from './routes/$slug.admin.dashboard'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateEventRoute = CreateEventRouteImport.update({
  id: '/create-event',
  path: '/create-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosedRoute = ClosedRouteImport.update({
  id: '/closed',
  path: '/closed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugAdminIndexRoute = SlugAdminIndexRouteImport.update({
  id: '/$slug/admin/',
  path: '/$slug/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExpireEventsRoute = ApiPublicExpireEventsRouteImport.update({
  id: '/api/public/expire-events',
  path: '/api/public/expire-events',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugAdminDashboardRoute = SlugAdminDashboardRouteImport.update({
  id: '/$slug/admin/dashboard',
  path: '/$slug/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/closed': typeof ClosedRoute
  '/create-event': typeof CreateEventRoute
  '/dashboard': typeof DashboardRoute
  '/e/$slug': typeof ESlugRoute
  '/$slug/admin/dashboard': typeof SlugAdminDashboardRoute
  '/api/public/expire-events': typeof ApiPublicExpireEventsRoute
  '/$slug/admin/': typeof SlugAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/closed': typeof ClosedRoute
  '/create-event': typeof CreateEventRoute
  '/dashboard': typeof DashboardRoute
  '/e/$slug': typeof ESlugRoute
  '/$slug/admin/dashboard': typeof SlugAdminDashboardRoute
  '/api/public/expire-events': typeof ApiPublicExpireEventsRoute
  '/$slug/admin': typeof SlugAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/closed': typeof ClosedRoute
  '/create-event': typeof CreateEventRoute
  '/dashboard': typeof DashboardRoute
  '/e/$slug': typeof ESlugRoute
  '/$slug/admin/dashboard': typeof SlugAdminDashboardRoute
  '/api/public/expire-events': typeof ApiPublicExpireEventsRoute
  '/$slug/admin/': typeof SlugAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/closed'
    | '/create-event'
    | '/dashboard'
    | '/e/$slug'
    | '/$slug/admin/dashboard'
    | '/api/public/expire-events'
    | '/$slug/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/closed'
    | '/create-event'
    | '/dashboard'
    | '/e/$slug'
    | '/$slug/admin/dashboard'
    | '/api/public/expire-events'
    | '/$slug/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/closed'
    | '/create-event'
    | '/dashboard'
    | '/e/$slug'
    | '/$slug/admin/dashboard'
    | '/api/public/expire-events'
    | '/$slug/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ClosedRoute: typeof ClosedRoute
  CreateEventRoute: typeof CreateEventRoute
  DashboardRoute: typeof DashboardRoute
  ESlugRoute: typeof ESlugRoute
  SlugAdminDashboardRoute: typeof SlugAdminDashboardRoute
  ApiPublicExpireEventsRoute: typeof ApiPublicExpireEventsRoute
  SlugAdminIndexRoute: typeof SlugAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-event': {
      id: '/create-event'
      path: '/create-event'
      fullPath: '/create-event'
      preLoaderRoute: typeof CreateEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closed': {
      id: '/closed'
      path: '/closed'
      fullPath: '/closed'
      preLoaderRoute: typeof ClosedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/admin/': {
      id: '/$slug/admin/'
      path: '/$slug/admin'
      fullPath: '/$slug/admin/'
      preLoaderRoute: typeof SlugAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/expire-events': {
      id: '/api/public/expire-events'
      path: '/api/public/expire-events'
      fullPath: '/api/public/expire-events'
      preLoaderRoute: typeof ApiPublicExpireEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/admin/dashboard': {
      id: '/$slug/admin/dashboard'
      path: '/$slug/admin/dashboard'
      fullPath: '/$slug/admin/dashboard'
      preLoaderRoute: typeof SlugAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ClosedRoute: ClosedRoute,
  CreateEventRoute: CreateEventRoute,
  DashboardRoute: DashboardRoute,
  ESlugRoute: ESlugRoute,
  SlugAdminDashboardRoute: SlugAdminDashboardRoute,
  ApiPublicExpireEventsRoute: ApiPublicExpireEventsRoute,
  SlugAdminIndexRoute: SlugAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
