/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClosedRouteImport } from './routes/closed'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugAdminRouteImport } from './routes/$slug.admin'

const ClosedRoute = ClosedRouteImport.update({
  id: '/closed',
  path: '/closed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugAdminRoute = SlugAdminRouteImport.update({
  id: '/$slug/admin',
  path: '/$slug/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/closed': typeof ClosedRoute
  '/$slug/admin': typeof SlugAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/closed': typeof ClosedRoute
  '/$slug/admin': typeof SlugAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/closed': typeof ClosedRoute
  '/$slug/admin': typeof SlugAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/closed' | '/$slug/admin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/closed' | '/$slug/admin'
  id: '__root__' | '/' | '/admin' | '/closed' | '/$slug/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ClosedRoute: typeof ClosedRoute
  SlugAdminRoute: typeof SlugAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/closed': {
      id: '/closed'
      path: '/closed'
      fullPath: '/closed'
      preLoaderRoute: typeof ClosedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/admin': {
      id: '/$slug/admin'
      path: '/$slug/admin'
      fullPath: '/$slug/admin'
      preLoaderRoute: typeof SlugAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ClosedRoute: ClosedRoute,
  SlugAdminRoute: SlugAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
